# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180511_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.TextField(),
        ),
    ]
